const default_events =
    [
    {
        "id": 0,
        "name": "Estudar AM1",
        "category": "Studying",
        "frequency": "None",
        "notification": "Never",
        "color": "rgb(255, 99, 132)",
        "description": "Estudar AM1",
        "start_date": 1,
        "end_date": 1,
        "start_time": [10, 15],
        "end_time": [14, 15],
        "start_date_time": "2021-12-01T10:15",
        "end_date_time": "2021-12-01T14:15"
    },
    {
        "id": 1,
        "name": "Chegar a Gold no LOL",
        "category": "Gaming",
        "frequency": "None",
        "notification": "Never",
        "color": "rgb(54, 162, 235)",
        "description": "Chegar a Gold no LOL",
        "start_date": 7,
        "end_date": 7,
        "start_time": [20, 5],
        "end_time": [23, 55],
        "start_date_time": "2021-12-07T20:05",
        "end_date_time": "2021-12-07T23:55"
    },
    {
        "id": 2,
        "name": "Jogar",
        "category": "Gaming",
        "frequency": "None",
        "notification": "Never",
        "color": "rgb(54, 162, 235)",
        "description": "Jogar",
        "start_date": 1,
        "end_date": 1,
        "start_time": [15, 0],
        "end_time": [19, 0],
        "start_date_time": "2021-12-01T15:00",
        "end_date_time": "2021-12-01T19:00"
    },
    {
        "id": 3,
        "name": "Dormir",
        "category": "Sleeping",
        "frequency": "None",
        "notification": "Never",
        "color": "rgb(255, 205, 86)",
        "description": "Dormir",
        "start_date": 1,
        "end_date": 2,
        "start_time": [22, 0],
        "end_time": [10, 0],
        "start_date_time": "2021-12-01T22:00",
        "end_date_time": "2021-12-02T10:00"
    },
    {
        "id": 4,
        "name": "Dormir",
        "category": "Sleeping",
        "frequency": "None",
        "notification": "Never",
        "color": "rgb(255, 205, 86)",
        "description": "Dormir",
        "start_date": 2,
        "end_date": 3,
        "start_time": [22, 0],
        "end_time": [10, 0],
        "start_date_time": "2021-12-02T22:00",
        "end_date_time": "2021-12-03T10:00"
    },
    {
        "id": 5,
        "name": "Dormir",
        "category": "Sleeping",
        "frequency": "None",
        "notification": "Never",
        "color": "rgb(255, 205, 86)",
        "description": "Dormir",
        "start_date": 3,
        "end_date": 4,
        "start_time": [22, 0],
        "end_time": [10, 0],
        "start_date_time": "2021-12-03T22:00",
        "end_date_time": "2021-12-04T10:00"
    },
    {
        "id": 6,
        "name": "Dormir",
        "category": "Sleeping",
        "frequency": "None",
        "notification": "Never",
        "color": "rgb(255, 205, 86)",
        "description": "Dormir",
        "start_date": 4,
        "end_date": 5,
        "start_time": [22, 0],
        "end_time": [10, 0],
        "start_date_time": "2021-12-04T22:00",
        "end_date_time": "2021-12-05T10:00"
    },
    {
        "id": 7,
        "name": "Dormir",
        "category": "Sleeping",
        "frequency": "None",
        "notification": "Never",
        "color": "rgb(255, 205, 86)",
        "description": "Dormir",
        "start_date": 5,
        "end_date": 6,
        "start_time": [22, 0],
        "end_time": [10, 0],
        "start_date_time": "2021-12-05T22:00",
        "end_date_time": "2021-12-06T10:00"
    },
    {
        "id": 8,
        "name": "Dormir",
        "category": "Sleeping",
        "frequency": "None",
        "notification": "Never",
        "color": "rgb(255, 205, 86)",
        "description": "Dormir",
        "start_date": 6,
        "end_date": 7,
        "start_time": [22, 0],
        "end_time": [10, 0],
        "start_date_time": "2021-12-06T22:00",
        "end_date_time": "2021-12-07T10:00"
    },
    {
        "id": 9,
        "name": "Jogar",
        "category": "Gaming",
        "frequency": "None",
        "notification": "Never",
        "color": "rgb(54, 162, 235)",
        "description": "Jogar",
        "start_date": 2,
        "end_date": 2,
        "start_time": [10, 1],
        "end_time": [15, 0],
        "start_date_time": "2021-12-02T10:01",
        "end_date_time": "2021-12-02T15:00"
    },
    {
        "id": 10,
        "name": "Teste de AM2",
        "category": "Studying",
        "frequency": "None",
        "notification": "Never",
        "color": "rgb(255, 99, 132)",
        "description": "Teste de AM2",
        "start_date": 2,
        "end_date": 2,
        "start_time": [16, 0],
        "end_time": [18, 0],
        "start_date_time": "2021-12-02T16:00",
        "end_date_time": "2021-12-02T18:00"
    },
    {
        "id": 11,
        "name": "Estudar IIO",
        "category": "Studying",
        "frequency": "None",
        "notification": "Never",
        "color": "rgb(255, 99, 132)",
        "description": "Estudar IIO",
        "start_date": 2,
        "end_date": 2,
        "start_time": [19, 1],
        "end_time": [21, 59],
        "start_date_time": "2021-12-02T19:01",
        "end_date_time": "2021-12-02T21:59"
    },
    {
        "id": 12,
        "name": "Netflix",
        "category": "Gaming",
        "frequency": "None",
        "notification": "Never",
        "color": "rgb(54, 162, 235)",
        "description": "Netflix",
        "start_date": 3,
        "end_date": 3,
        "start_time": [10, 1],
        "end_time": [21, 59],
        "start_date_time": "2021-12-03T10:01",
        "end_date_time": "2021-12-03T21:59"
    },
    {
        "id": 13,
        "name": "Jogar",
        "category": "Gaming",
        "frequency": "None",
        "notification": "Never",
        "color": "rgb(54, 162, 235)",
        "description": "Jogar",
        "start_date": 4,
        "end_date": 4,
        "start_time": [10, 1],
        "end_time": [21, 59],
        "start_date_time": "2021-12-04T10:01",
        "end_date_time": "2021-12-04T21:59"
    },
    {
        "id": 14,
        "name": "Estudar",
        "category": "Studying",
        "frequency": "None",
        "notification": "Never",
        "color": "rgb(255, 99, 132)",
        "description": "Estudar",
        "start_date": 5,
        "end_date": 5,
        "start_time": [10, 1],
        "end_time": [21, 59],
        "start_date_time": "2021-12-05T10:01",
        "end_date_time": "2021-12-05T21:59"
    },
    {
        "id": 15,
        "name": "Cuidar do Jose",
        "category": "Exercising",
        "frequency": "None",
        "notification": "Never",
        "color": "#3cba9f",
        "description": "Que bebe chato, so me interessa o dinheiro",
        "start_date": 5,
        "end_date": 5,
        "start_time": [17, 0],
        "end_time": [19, 0],
        "start_date_time": "2021-12-05T17:00",
        "end_date_time": "2021-12-05T19:00"
    },
    {
        "id": 16,
        "name": "Gym - Bicep day :)",
        "category": "Exercising",
        "frequency": "None",
        "notification": "Never",
        "color": "#3cba9f",
        "description": "Hoje era suposto ser pernas mas pronto",
        "start_date": 6,
        "end_date": 6,
        "start_time": [10, 1],
        "end_time": [13, 0],
        "start_date_time": "2021-12-06T10:01",
        "end_date_time": "2021-12-06T13:00"
    },
    {
        "id": 17,
        "name": "Reach Grand Champ in RL",
        "category": "Gaming",
        "frequency": "None",
        "notification": "Never",
        "color": "rgb(54, 162, 235)",
        "description": "I can do it! Im already Champ 3!",
        "start_date": 6,
        "end_date": 6,
        "start_time": [13, 1],
        "end_time": [21, 59],
        "start_date_time": "2021-12-06T13:01",
        "end_date_time": "2021-12-06T21:59"
    },
    {
        "id": 18,
        "name": "Estudar IPM",
        "category": "Studying",
        "frequency": "None",
        "notification": "Never",
        "color": "rgb(255, 99, 132)",
        "description": "Ew qui nojo",
        "start_date": 7,
        "end_date": 7,
        "start_time": [10, 1],
        "end_time": [20, 4],
        "start_date_time": "2021-12-07T10:01",
        "end_date_time": "2021-12-07T20:04"
    }
];
