const default_events =
    [
    {
        "id": 0,
        "name": "Estudar AM1",
        "category": "Studying",
        "frequency": "None",
        "notification": "Never",
        "color": "#f54242",
        "description": "Tou tramado",
        "start_date": 1,
        "end_date": 1,
        "start_time": [9, 15],
        "end_time": [14, 15],
        "start_date_time": "2021-12-01T09:15",
        "end_date_time": "2021-12-02T09:15"
    },
    {
        "id": 1,
        "name": "Estudar AM2",
        "category": "Studying",
        "frequency": "None",
        "notification": "Never",
        "color": "#f54242",
        "description": "Tou tramado 2",
        "start_date": 2,
        "end_date": 3,
        "start_time": [19, 15],
        "end_time": [19, 15],
        "start_date_time": "2021-12-02T19:15",
        "end_date_time": "2021-12-03T19:15"
    },
    {
        "id": 2,
        "name": "Estudar IIO",
        "category": "Studying",
        "frequency": "None",
        "notification": "Never",
        "color": "#f54242",
        "description": "Tas fixinho",
        "start_date": 4,
        "end_date": 4,
        "start_time": [9, 15],
        "end_time": [9, 45],
        "start_date_time": "2021-12-04T09:15",
        "end_date_time": "2021-12-04T09:45"
    },
    {
        "id": 3,
        "name": "Cuidar do Jose",
        "category": "Exercising",
        "frequency": "None",
        "notification": "Never",
        "color": "#42bcf5",
        "description": "Que bebe chato, so me interessa o dinheiro",
        "start_date": 5,
        "end_date": 5,
        "start_time": [17, 0],
        "end_time": [19, 0],
        "start_date_time": "2021-12-05T17:00",
        "end_date_time": "2021-12-05T19:00"
    },
    {
        "id": 4,
        "name": "Dormir",
        "category": "Sleeping",
        "frequency": "None",
        "notification": "Never",
        "color": "#cb42f5",
        "description": "As vezes sonho com a Maria",
        "start_date": 5,
        "end_date": 7,
        "start_time": [20, 0],
        "end_time": [20, 0],
        "start_date_time": "2021-12-05T20:00",
        "end_date_time": "2021-12-07T20:00"
    },
    {
        "id": 5,
        "name": "Chegar a Gold no LOL",
        "category": "Gaming",
        "frequency": "None",
        "notification": "Never",
        "color": "#54f542",
        "description": "SO FEEDERS PA PORRA O MEU JUNGLER NEM GANKA FF15",
        "start_date": 7,
        "end_date": 7,
        "start_time": [20, 5],
        "end_time": [23, 55],
        "start_date_time": "2021-12-07T20:05",
        "end_date_time": "2021-12-07T23:55"
    },
    {
        "id": 6,
        "name": "Jogar",
        "category": "Gaming",
        "frequency": "None",
        "notification": "Never",
        "color": "#f54242",
        "description": "Tou tramado 2",
        "start_date": 1,
        "end_date": 1,
        "start_time": [15, 0],
        "end_time": [19, 0],
        "start_date_time": "2021-12-02T19:15",
        "end_date_time": "2021-12-03T19:15"
    },
    {
        "id": 8,
        "name": "Dormir",
        "category": "Sleeping",
        "frequency": "None",
        "notification": "Never",
        "color": "#f54242",
        "description": "Tou tramado 2",
        "start_date": 1,
        "end_date": 2,
        "start_time": [22, 0],
        "end_time": [10, 0],
        "start_date_time": "2021-12-02T19:15",
        "end_date_time": "2021-12-03T19:15"
    },
    {
        "id": 9,
        "name": "Jogar",
        "category": "Gaming",
        "frequency": "None",
        "notification": "Never",
        "color": "#f54242",
        "description": "Tou tramado 2",
        "start_date": 2,
        "end_date": 2,
        "start_time": [10, 0],
        "end_time": [15, 0],
        "start_date_time": "2021-12-02T19:15",
        "end_date_time": "2021-12-03T19:15"
    },
    {
        "id": 10,
        "name": "Teste AM2",
        "category": "Studying",
        "frequency": "None",
        "notification": "Never",
        "color": "#f54242",
        "description": "Tou tramado 2",
        "start_date": 2,
        "end_date": 2,
        "start_time": [16, 0],
        "end_time": [18, 0],
        "start_date_time": "2021-12-02T19:15",
        "end_date_time": "2021-12-03T19:15"
    }
];

